// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  TopViewer.LightingSetup = (function() {
    function LightingSetup(name, lightPosition) {
      this.name = name;
      this.lightPosition = lightPosition;
    }

    return LightingSetup;

  })();

}).call(this);
